syntax = "proto3";

package messages.v1;

service MessagesService {
    rpc CreateMessage (CreateMessageRequest) returns (MessageResponse);
    rpc GetMessage (GetMessageRequest) returns (MessageResponse);
    rpc ListMessages (ListMessagesRequest) returns (ListMessagesResponse);
    rpc SubscribeMessages (SubscribeRequest) returns (stream MessageResponse);
}

message CreateMessageRequest {
    string name = 1;
    string topic = 2;
}

message GetMessageRequest {
    int32 id = 1;
}

message ListMessagesRequest {}

message SubscribeRequest {}

message MessageResponse {
    int32 id = 1;
    string name = 2;
    string topic = 3;
    string created_at = 4;
}

message ListMessagesResponse {
    repeated MessageResponse messages = 1;
}