apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.repository | default "tickets-svc" }}
  labels:
    app: {{ .Values.image.repository | default "tickets-app" }}
spec:
  selector:
    app: {{ .Values.image.repository | default "tickets-app" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  type: {{ .Values.service.type }}